spring:
  application:
    name: UberClientSocketService
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "sample-group"

  datasource:
    url: jdbc:mysql://mysql-13f24328-pptl8685-9946.b.aivencloud.com:16510/defaultdb
    username: avnadmin
    password: AVNS_I_rzbISG46QB8AW4RZI
    # password: ${ENV_MYSQL_PASSWORD}  # Access environment variable like this

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
  instance:
    prefer-ip-address: true