spring:
  application:
    name: "UberLocationService"
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 6000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
  instance:
    prefer-ip-address: true